backend:
  name: github
  repo: OstaraBlue/mysite
  branch: master

public_folder: ".vuepress/dist/"
media_folder: ".vuepress/dist/assets/img"

collections:
  - name: "Blog"
    label: "Post"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "date", format: "YYYY-MM-DD"}
      - {label: "Description" name: "description", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}

